eureka:
  instance:
    hostname: RegistrationCenter
  client:
    serviceUrl:
      defaultZone: http://registration-center:registration-center@127.0.0.1:8761/eureka
  server:
    enable-self-preservation: false
    peer-node-read-timeout-ms: 500
  environment: prod
  